#Project generated by Animated Java (https://animated-java.dev/)

tag @s add aj.maiden.anim.iron.maiden.animation
execute if score .aj.maiden.framerate aj.i matches ..-1 run scoreboard players set @s aj.frame4 37
execute if score .aj.maiden.framerate aj.i matches 1.. run scoreboard players set @s aj.frame4 0
scoreboard players add .noScripts aj.i4 0
execute if score .aj.anim_loop aj.maiden.animating matches 0 run function maiden:animation_loop
scoreboard players set #execute aj.i4 1