#Project generated by Animated Java (https://animated-java.dev/)

tag @s remove aj.maiden.anim.iron.maiden.animation
scoreboard players set @s aj.frame4 0
scoreboard players operation .oldValue aj.i4 = .noScripts aj.i4
scoreboard players set .noScripts aj.i4 1
function maiden:animations/iron.maiden.animation/next_frame
scoreboard players operation .noScripts aj.i4 = .oldValue aj.i4
scoreboard players set @s aj.frame4 0
scoreboard players set #execute aj.i4 1