#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:armor_stand ~ ~ ~ {Invisible:1,Tags:['global','maiden','new','aj.maiden','aj.maiden.root']}
execute as @e[type=minecraft:armor_stand,tag=aj.maiden.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function maiden:summon/zzz/execute/2
function maiden:assert_animation_flags
