#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.blutopher.root] rotated ~ 0 run function blutopher:zzz/conditional/4
execute if score #execute aj.i matches 0 run function blutopher:zzz/conditional/5