#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.blutopher.anim.first.snap] at @s run function blutopher:animations/first.snap/next_frame
scoreboard players operation @s aj.blutopher.animating = .aj.animation aj.blutopher.animating