#Project generated by Animated Java (https://animated-java.dev/)

tp @s[tag=aj.blutopher.bone.jaw1] ^-0.002 ^-1.806 ^-0.084
tp @s[tag=aj.blutopher.bone.jaw2] ^0.002 ^-1.806 ^0.092
tp @s[tag=aj.blutopher.bone.jaw3] ^0.002 ^-1.806 ^0.092
tp @s[tag=aj.blutopher.bone.jaw4] ^-0.002 ^-1.806 ^-0.084
tp @s[tag=aj.blutopher.bone.jaw5] ^-0.002 ^-1.806 ^-0.366
tp @s[tag=aj.blutopher.bone.jaw6] ^0.002 ^-1.806 ^0.394
execute store result score .calc aj.i run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i 2