#Project generated by Animated Java (https://animated-java.dev/)

data modify entity @s[tag=aj.blutopher.bone.jaw1] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.blutopher.bone.jaw2] Pose.Head set value [-180f,0f,180f]
data modify entity @s[tag=aj.blutopher.bone.jaw3] Pose.Head set value [-180f,0f,180f]
data modify entity @s[tag=aj.blutopher.bone.jaw4] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.blutopher.bone.jaw5] Pose.Head set value [0f,0f,0f]
data modify entity @s[tag=aj.blutopher.bone.jaw6] Pose.Head set value [-180f,0f,180f]
tp @s ~ ~ ~ ~ ~