#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i 1
execute at @s as @e[type=#blutopher:bone_entities,tag=aj.blutopher.bone] if score @s aj.id = .this aj.id run function blutopher:zzz/execute/8