#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #uninstall aj.i4 0
scoreboard objectives remove aj.i4
scoreboard objectives remove aj.id4
scoreboard objectives remove aj.frame4
tellraw @a [{"text":"Removed AJ specific scoreboard objectives:","color":"green"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.i4","color":"aqua"},{"text":" (Internal)","color":"dark_gray"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.id4","color":"aqua"},{"text":" (ID)","color":"dark_gray"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.frame4","color":"aqua"},{"text":" (Frame)","color":"dark_gray"}]