#Project generated by Animated Java (https://animated-java.dev/)

summon minecraft:armor_stand ~ ~ ~ {NoGravity:1,Invisible:1,Tags:['global','bluto','new','aj.blutopher','aj.blutopher.root']}
execute as @e[type=minecraft:armor_stand,tag=aj.blutopher.root,tag=new,distance=..1,limit=1] rotated ~ 0 run function blutopher:summon/zzz/execute/2
function blutopher:assert_animation_flags
