#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.blutopher.first.snap.loopMode matches 0 run function blutopher:animations/first.snap/stop
execute if score @s aj.blutopher.first.snap.loopMode matches 1 run function blutopher:animations/first.snap/pause
execute if score @s aj.blutopher.first.snap.loopMode matches 2 run function blutopher:animations/first.snap/zzz/execute/13