#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id = @s aj.id
scoreboard players operation .this aj.frame = @s aj.frame
execute rotated ~ 0 as @e[type=#blutopher:bone_entities,tag=aj.blutopher.bone,distance=..6.1739999999999995] if score @s aj.id = .this aj.id run function blutopher:animations/first.snap/tree/trunk
scoreboard players operation @s aj.frame += .aj.blutopher.framerate aj.i
scoreboard players set .aj.animation aj.blutopher.animating 1
execute unless score @s aj.frame matches 0..13 run function blutopher:animations/first.snap/edge