#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i 0
execute if entity @s[tag=aj.blutopher.root] run function blutopher:animations/first.snap/zzz/conditional/12
execute if score #execute aj.i matches 0 run function blutopher:animations/first.snap/zzz/conditional/13