#Project generated by Animated Java (https://animated-java.dev/)

execute at @s as @e[type=minecraft:area_effect_cloud,tag=aj.maiden.bone] if score @s aj.id4 = .this aj.id4 run tp @s ~ ~ ~
function maiden:reset