#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.maiden.anim.iron.maiden.animation] at @s run function maiden:animations/iron.maiden.animation/next_frame
scoreboard players operation @s aj.maiden.animating = .aj.animation aj.maiden.animating