#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set # aj.i4 1
execute at @s as @e[type=#maiden:bone_entities,tag=aj.maiden.bone] if score @s aj.id4 = .this aj.id4 run function maiden:zzz/execute/8