#Project generated by Animated Java (https://animated-java.dev/)

function maiden:animations/iron.maiden.animation/tree/root_bone_name
execute store result score .calc aj.i4 run data get entity @s Air
execute store result entity @s Air short 1 run scoreboard players add .calc aj.i4 2