#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation # aj.id = @s aj.id
execute as @e[type=#blutopher:bone_entities,tag=aj.blutopher,distance=..7.887] if score @s aj.id = # aj.id run kill @s
kill @s
scoreboard players set #execute aj.i 1