#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players add .aj.animation aj.maiden.animating 0
scoreboard players add .aj.anim_loop aj.maiden.animating 0
scoreboard players add .noScripts aj.i4 0