#Project generated by Animated Java (https://animated-java.dev/)

scoreboard objectives add aj.i4 dummy
scoreboard objectives add aj.id4 dummy
scoreboard objectives add aj.frame4 dummy
scoreboard objectives add aj.maiden.animating dummy
scoreboard objectives add aj.maiden.iron.maiden.animation.loopMode dummy
function maiden:reset_animation_flags
scoreboard players set #uninstall aj.i4 0
scoreboard players set .aj.maiden.framerate aj.i4 1
#tellraw @a [{"text":"[ ","color":"dark_gray"},{"text":"AJ","color":"aqua"},{"text":" → ","color":"gray"},{"text":"Install ⊻","color":"green"},{"text":" ]","color":"dark_gray"},"\n",{"text":"Installed ","color":"gray"},{"text":"armor_stand","color":"gold"},{"text":" rig.","color":"gray"},"\n",{"text":"◘ ","color":"gray"},{"text":"Included Scoreboard Objectives:","color":"green"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.i4","color":"aqua"},{"text":" (Internal)","color":"dark_gray"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.id4","color":"aqua"},{"text":" (ID)","color":"dark_gray"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.frame4","color":"aqua"},{"text":" (Frame)","color":"dark_gray"},"\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.maiden.animating","color":"aqua"},{"text":" (Animation Flag)","color":"dark_gray"},[["\n",{"text":"   ◘ ","color":"gray"},{"text":"aj.maiden.iron.maiden.animation.loopMode","color":"aqua"},{"text":" (Loop Mode)","color":"dark_gray"}]]]
