#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i4 0
execute if entity @s[tag=aj.maiden.root] rotated ~ 0 run function maiden:zzz/conditional/4
execute if score #execute aj.i4 matches 0 run function maiden:zzz/conditional/5