#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set .aj.animation aj.maiden.animating 0
scoreboard players set .aj.anim_loop aj.maiden.animating 0
scoreboard players set .noScripts aj.i4 0