#Project generated by Animated Java (https://animated-java.dev/)

tp @s ~ ~ ~ ~ ~
execute store result score @s aj.id4 run scoreboard players add .aj.last_id aj.i4 1
execute at @s run function maiden:summon/zzz/execute/3
tag @s remove new
scoreboard players set @s aj.maiden.iron.maiden.animation.loopMode 0
scoreboard players set @s aj.frame4 0
scoreboard players set @s aj.maiden.animating 0