#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i4 0
execute if entity @s[tag=aj.maiden.root] at @s run function maiden:remove/zzz/conditional/0
execute if score #execute aj.i4 matches 0 run function maiden:remove/zzz/conditional/1