#Project generated by Animated Java (https://animated-java.dev/)

execute if score @s aj.maiden.iron.maiden.animation.loopMode matches 0 run function maiden:animations/iron.maiden.animation/stop
execute if score @s aj.maiden.iron.maiden.animation.loopMode matches 1 run function maiden:animations/iron.maiden.animation/pause
execute if score @s aj.maiden.iron.maiden.animation.loopMode matches 2 run function maiden:animations/iron.maiden.animation/zzz/execute/13