#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation .this aj.id4 = @s aj.id4
scoreboard players operation .this aj.frame4 = @s aj.frame4
execute rotated ~ 0 as @e[type=#maiden:bone_entities,tag=aj.maiden.bone,distance=..7.978] if score @s aj.id4 = .this aj.id4 run function maiden:animations/iron.maiden.animation/tree/trunk
scoreboard players operation @s aj.frame4 += .aj.maiden.framerate aj.i4
scoreboard players set .aj.animation aj.maiden.animating 1
execute unless score @s aj.frame4 matches 0..37 run function maiden:animations/iron.maiden.animation/edge