#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players operation # aj.id4 = @s aj.id4
execute as @e[type=#maiden:bone_entities,tag=aj.maiden,distance=..9.691] if score @s aj.id4 = # aj.id4 run kill @s
kill @s
scoreboard players set #execute aj.i4 1