#Project generated by Animated Java (https://animated-java.dev/)

scoreboard players set #execute aj.i4 0
execute if score @s aj.frame4 matches ..1 run function maiden:animations/iron.maiden.animation/zzz/conditional/14
execute if score #execute aj.i4 matches 0 run function maiden:animations/iron.maiden.animation/zzz/conditional/15