#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 0 run data modify entity @s Pose.Head set value [35f,0f,0f]
execute if score .this aj.frame4 matches 36 run data modify entity @s Pose.Head set value [35f,0f,0f]