#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 26 run tp @s ^0 ^0.687 ^0 ~ ~
execute if score .this aj.frame4 matches 27 run tp @s ^-0.031 ^0.687 ^0 ~ ~
execute if score .this aj.frame4 matches 28 run tp @s ^0.016 ^0.687 ^0 ~ ~
execute if score .this aj.frame4 matches 29 run tp @s ^-0.034 ^0.687 ^0 ~ ~
execute if score .this aj.frame4 matches 30 run tp @s ^0.063 ^0.687 ^0 ~ ~
execute if score .this aj.frame4 matches 31 run tp @s ^-0.028 ^0.687 ^0 ~ ~