#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 0 run data modify entity @s Pose.Head set value [0f,-90f,35f]
execute if score .this aj.frame4 matches 36 run data modify entity @s Pose.Head set value [0f,-90f,35f]