#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 32 run tp @s ^-0.484 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 33 run tp @s ^-0.494 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 34 run tp @s ^-0.506 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 35 run tp @s ^-0.484 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 36 run tp @s ^-0.5 ^-0.75 ^0 ~ ~