#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 0 run tp @s ^0.5 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 24..31 run function maiden:animations/iron.maiden.animation/tree/door1_root_24-31
execute if score .this aj.frame4 matches 32..36 run function maiden:animations/iron.maiden.animation/tree/door1_root_32-36