#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 26 run tp @s ^0.5 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 27 run tp @s ^0.469 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 28 run tp @s ^0.516 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 29 run tp @s ^0.466 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 30 run tp @s ^0.563 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 31 run tp @s ^0.472 ^-0.75 ^0 ~ ~