#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 26 run tp @s ^-0.5 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 27 run tp @s ^-0.531 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 28 run tp @s ^-0.484 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 29 run tp @s ^-0.534 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 30 run tp @s ^-0.437 ^-0.75 ^0 ~ ~
execute if score .this aj.frame4 matches 31 run tp @s ^-0.528 ^-0.75 ^0 ~ ~