#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 8 run data modify entity @s Pose.Head set value [-180f,65.64f,180f]
execute if score .this aj.frame4 matches 9 run data modify entity @s Pose.Head set value [-180f,76.92f,180f]
execute if score .this aj.frame4 matches 10 run data modify entity @s Pose.Head set value [-180f,88.2f,180f]
execute if score .this aj.frame4 matches 11 run data modify entity @s Pose.Head set value [0f,80.52f,0f]
execute if score .this aj.frame4 matches 12 run data modify entity @s Pose.Head set value [0f,70.6f,0f]
execute if score .this aj.frame4 matches 13 run data modify entity @s Pose.Head set value [0f,64.6f,0f]
execute if score .this aj.frame4 matches 14 run data modify entity @s Pose.Head set value [0f,61.4f,0f]
execute if score .this aj.frame4 matches 15 run data modify entity @s Pose.Head set value [0f,60f,0f]