#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 0 run data modify entity @s Pose.Head set value [180f,22.5f,0f]
execute if score .this aj.frame4 matches 1 run data modify entity @s Pose.Head set value [-180f,23.9f,0f]
execute if score .this aj.frame4 matches 2 run data modify entity @s Pose.Head set value [-180f,27.1f,0f]
execute if score .this aj.frame4 matches 3 run data modify entity @s Pose.Head set value [-180f,33.1f,0f]
execute if score .this aj.frame4 matches 4 run data modify entity @s Pose.Head set value [-180f,43.02f,0f]
execute if score .this aj.frame4 matches 5 run data modify entity @s Pose.Head set value [180f,54.3f,0f]
execute if score .this aj.frame4 matches 6 run data modify entity @s Pose.Head set value [-180f,65.58f,0f]
execute if score .this aj.frame4 matches 7 run data modify entity @s Pose.Head set value [-180f,76.86f,0f]