#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 8 run data modify entity @s Pose.Head set value [0f,46.86f,0f]
execute if score .this aj.frame4 matches 9 run data modify entity @s Pose.Head set value [0f,35.58f,0f]
execute if score .this aj.frame4 matches 10 run data modify entity @s Pose.Head set value [0f,24.3f,0f]
execute if score .this aj.frame4 matches 11 run data modify entity @s Pose.Head set value [0f,13.02f,0f]
execute if score .this aj.frame4 matches 12 run data modify entity @s Pose.Head set value [0f,3.1f,0f]
execute if score .this aj.frame4 matches 13 run data modify entity @s Pose.Head set value [0f,-2.9f,0f]
execute if score .this aj.frame4 matches 14 run data modify entity @s Pose.Head set value [0f,-6.1f,0f]
execute if score .this aj.frame4 matches 15 run data modify entity @s Pose.Head set value [0f,-7.5f,0f]