#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 20 run data modify entity @s Pose.Head set value [0f,37.5f,-180f]
execute if score .this aj.frame4 matches 21 run data modify entity @s Pose.Head set value [0f,37.7f,-180f]
execute if score .this aj.frame4 matches 22 run data modify entity @s Pose.Head set value [0f,39.3f,-180f]
execute if score .this aj.frame4 matches 23 run data modify entity @s Pose.Head set value [0f,42.9f,-180f]