#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 24 run tp @s ^-0.656 ^0.125 ^0.475 ~ ~
execute if score .this aj.frame4 matches 25 run tp @s ^-0.544 ^0.125 ^0.498 ~ ~
execute if score .this aj.frame4 matches 26 run tp @s ^-0.238 ^0.125 ^0.426 ~ ~
execute if score .this aj.frame4 matches 27 run tp @s ^-0.031 ^0.125 ^0 ~ ~
execute if score .this aj.frame4 matches 28 run tp @s ^0.016 ^0.125 ^0 ~ ~
execute if score .this aj.frame4 matches 29 run tp @s ^-0.034 ^0.125 ^0 ~ ~
execute if score .this aj.frame4 matches 30 run tp @s ^0.063 ^0.125 ^0 ~ ~
execute if score .this aj.frame4 matches 31 run tp @s ^-0.028 ^0.125 ^0 ~ ~