#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 8 run data modify entity @s Pose.Head set value [-180f,88.14f,0f]
execute if score .this aj.frame4 matches 9 run data modify entity @s Pose.Head set value [0f,80.58f,-180f]
execute if score .this aj.frame4 matches 10 run data modify entity @s Pose.Head set value [0f,69.3f,-180f]
execute if score .this aj.frame4 matches 11 run data modify entity @s Pose.Head set value [0f,58.02f,-180f]
execute if score .this aj.frame4 matches 12 run data modify entity @s Pose.Head set value [0f,48.1f,-180f]
execute if score .this aj.frame4 matches 13 run data modify entity @s Pose.Head set value [0f,42.1f,-180f]
execute if score .this aj.frame4 matches 14 run data modify entity @s Pose.Head set value [0f,38.9f,-180f]
execute if score .this aj.frame4 matches 15 run data modify entity @s Pose.Head set value [0f,37.5f,-180f]