#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 20 run tp @s ^0.75 ^-1.625 ^0.433 ~ ~
execute if score .this aj.frame4 matches 21 run tp @s ^0.748 ^-1.625 ^0.434 ~ ~
execute if score .this aj.frame4 matches 22 run tp @s ^0.736 ^-1.625 ^0.441 ~ ~
execute if score .this aj.frame4 matches 23 run tp @s ^0.708 ^-1.625 ^0.455 ~ ~