#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 0..7 run function maiden:animations/iron.maiden.animation/tree/sideoutspike30_root_0-7
execute if score .this aj.frame4 matches 8..15 run function maiden:animations/iron.maiden.animation/tree/sideoutspike30_root_8-15
execute if score .this aj.frame4 matches 16..23 run function maiden:animations/iron.maiden.animation/tree/sideoutspike30_root_16-23
execute if score .this aj.frame4 matches 24..31 run function maiden:animations/iron.maiden.animation/tree/sideoutspike30_root_24-31
execute if score .this aj.frame4 matches 32..36 run function maiden:animations/iron.maiden.animation/tree/sideoutspike30_root_32-36