#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 20 run tp @s ^-0.75 ^0.125 ^0.433 ~ ~
execute if score .this aj.frame4 matches 21 run tp @s ^-0.748 ^0.125 ^0.434 ~ ~
execute if score .this aj.frame4 matches 22 run tp @s ^-0.736 ^0.125 ^0.441 ~ ~
execute if score .this aj.frame4 matches 23 run tp @s ^-0.708 ^0.125 ^0.455 ~ ~