#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 24 run data modify entity @s Pose.Head set value [0f,71.8f,0f]
execute if score .this aj.frame4 matches 25 run data modify entity @s Pose.Head set value [0f,85f,0f]
execute if score .this aj.frame4 matches 26 run data modify entity @s Pose.Head set value [-180f,58.4f,180f]
execute if score .this aj.frame4 matches 27 run data modify entity @s Pose.Head set value [-180f,0f,180f]