#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 0 run data modify entity @s Pose.Head set value [-180f,0f,0f]
execute if score .this aj.frame4 matches 1 run data modify entity @s Pose.Head set value [-180f,1.4f,0f]
execute if score .this aj.frame4 matches 2 run data modify entity @s Pose.Head set value [-180f,4.6f,0f]
execute if score .this aj.frame4 matches 3 run data modify entity @s Pose.Head set value [-180f,10.6f,0f]
execute if score .this aj.frame4 matches 4 run data modify entity @s Pose.Head set value [-180f,20.52f,0f]
execute if score .this aj.frame4 matches 5 run data modify entity @s Pose.Head set value [-180f,31.8f,0f]
execute if score .this aj.frame4 matches 6 run data modify entity @s Pose.Head set value [180f,43.08f,0f]
execute if score .this aj.frame4 matches 7 run data modify entity @s Pose.Head set value [-180f,54.36f,0f]