#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 0 run tp @s ^0 ^-1.625 ^0 ~ ~
execute if score .this aj.frame4 matches 1 run tp @s ^0 ^-1.625 ^0.012 ~ ~
execute if score .this aj.frame4 matches 2 run tp @s ^0.002 ^-1.625 ^0.04 ~ ~
execute if score .this aj.frame4 matches 3 run tp @s ^0.009 ^-1.625 ^0.092 ~ ~
execute if score .this aj.frame4 matches 4 run tp @s ^0.032 ^-1.625 ^0.175 ~ ~
execute if score .this aj.frame4 matches 5 run tp @s ^0.075 ^-1.625 ^0.263 ~ ~
execute if score .this aj.frame4 matches 6 run tp @s ^0.135 ^-1.625 ^0.342 ~ ~
execute if score .this aj.frame4 matches 7 run tp @s ^0.209 ^-1.625 ^0.406 ~ ~