#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 8 run data modify entity @s Pose.Head set value [0f,69.36f,0f]
execute if score .this aj.frame4 matches 9 run data modify entity @s Pose.Head set value [0f,58.08f,0f]
execute if score .this aj.frame4 matches 10 run data modify entity @s Pose.Head set value [0f,46.8f,0f]
execute if score .this aj.frame4 matches 11 run data modify entity @s Pose.Head set value [0f,35.52f,0f]
execute if score .this aj.frame4 matches 12 run data modify entity @s Pose.Head set value [0f,25.6f,0f]
execute if score .this aj.frame4 matches 13 run data modify entity @s Pose.Head set value [0f,19.6f,0f]
execute if score .this aj.frame4 matches 14 run data modify entity @s Pose.Head set value [0f,16.4f,0f]
execute if score .this aj.frame4 matches 15 run data modify entity @s Pose.Head set value [0f,15f,0f]