#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 24 run data modify entity @s Pose.Head set value [0f,26.8f,-180f]
execute if score .this aj.frame4 matches 25 run data modify entity @s Pose.Head set value [0f,40f,-180f]
execute if score .this aj.frame4 matches 26 run data modify entity @s Pose.Head set value [0f,76.6f,-180f]
execute if score .this aj.frame4 matches 27 run data modify entity @s Pose.Head set value [-180f,45f,0f]