#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 20 run data modify entity @s Pose.Head set value [0f,60f,0f]
execute if score .this aj.frame4 matches 21 run data modify entity @s Pose.Head set value [0f,60.2f,0f]
execute if score .this aj.frame4 matches 22 run data modify entity @s Pose.Head set value [0f,61.8f,0f]
execute if score .this aj.frame4 matches 23 run data modify entity @s Pose.Head set value [0f,65.4f,0f]