#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 32 run tp @s ^0.016 ^-0.188 ^0 ~ ~
execute if score .this aj.frame4 matches 33 run tp @s ^0.006 ^-0.188 ^0 ~ ~
execute if score .this aj.frame4 matches 34 run tp @s ^-0.006 ^-0.188 ^0 ~ ~
execute if score .this aj.frame4 matches 35 run tp @s ^0.016 ^-0.188 ^0 ~ ~
execute if score .this aj.frame4 matches 36 run tp @s ^0 ^-0.188 ^0 ~ ~