#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 0 run data modify entity @s Pose.Head set value [-180f,67.5f,0f]
execute if score .this aj.frame4 matches 1 run data modify entity @s Pose.Head set value [-180f,68.9f,0f]
execute if score .this aj.frame4 matches 2 run data modify entity @s Pose.Head set value [-180f,72.1f,0f]
execute if score .this aj.frame4 matches 3 run data modify entity @s Pose.Head set value [-180f,78.1f,0f]
execute if score .this aj.frame4 matches 4 run data modify entity @s Pose.Head set value [-180f,88.02f,0f]
execute if score .this aj.frame4 matches 5 run data modify entity @s Pose.Head set value [0f,80.7f,-180f]
execute if score .this aj.frame4 matches 6 run data modify entity @s Pose.Head set value [0f,69.42f,-180f]
execute if score .this aj.frame4 matches 7 run data modify entity @s Pose.Head set value [0f,58.14f,-180f]