#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 0 run data modify entity @s Pose.Head set value [-180f,45f,180f]
execute if score .this aj.frame4 matches 1 run data modify entity @s Pose.Head set value [-180f,46.4f,180f]
execute if score .this aj.frame4 matches 2 run data modify entity @s Pose.Head set value [-180f,49.6f,180f]
execute if score .this aj.frame4 matches 3 run data modify entity @s Pose.Head set value [-180f,55.6f,180f]
execute if score .this aj.frame4 matches 4 run data modify entity @s Pose.Head set value [-180f,65.52f,180f]
execute if score .this aj.frame4 matches 5 run data modify entity @s Pose.Head set value [-180f,76.8f,180f]
execute if score .this aj.frame4 matches 6 run data modify entity @s Pose.Head set value [-180f,88.08f,180f]
execute if score .this aj.frame4 matches 7 run data modify entity @s Pose.Head set value [0f,80.64f,0f]