#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 24 run data modify entity @s Pose.Head set value [0f,4.3f,-180f]
execute if score .this aj.frame4 matches 25 run data modify entity @s Pose.Head set value [0f,17.5f,-180f]
execute if score .this aj.frame4 matches 26 run data modify entity @s Pose.Head set value [0f,54.1f,-180f]
execute if score .this aj.frame4 matches 27 run data modify entity @s Pose.Head set value [-180f,67.5f,0f]