#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame4 matches 8 run tp @s ^0.294 ^-1.313 ^0.455 ~ ~
execute if score .this aj.frame4 matches 9 run tp @s ^0.387 ^-1.313 ^0.487 ~ ~
execute if score .this aj.frame4 matches 10 run tp @s ^0.484 ^-1.313 ^0.5 ~ ~
execute if score .this aj.frame4 matches 11 run tp @s ^0.582 ^-1.313 ^0.493 ~ ~
execute if score .this aj.frame4 matches 12 run tp @s ^0.666 ^-1.313 ^0.472 ~ ~
execute if score .this aj.frame4 matches 13 run tp @s ^0.714 ^-1.313 ^0.452 ~ ~
execute if score .this aj.frame4 matches 14 run tp @s ^0.739 ^-1.313 ^0.439 ~ ~
execute if score .this aj.frame4 matches 15 run tp @s ^0.75 ^-1.313 ^0.433 ~ ~