#Project generated by Animated Java (https://animated-java.dev/)

execute if entity @s[tag=aj.blutopher.bone.jaw1] run function blutopher:animations/first.snap/tree/jaw1_display_top
execute if entity @s[tag=aj.blutopher.bone.jaw2] run function blutopher:animations/first.snap/tree/jaw2_display_top
execute if entity @s[tag=aj.blutopher.bone.jaw3] run function blutopher:animations/first.snap/tree/jaw3_display_top
execute if entity @s[tag=aj.blutopher.bone.jaw4] run function blutopher:animations/first.snap/tree/jaw4_display_top
execute if entity @s[tag=aj.blutopher.bone.jaw5] run function blutopher:animations/first.snap/tree/jaw5_display_top
execute if entity @s[tag=aj.blutopher.bone.jaw6] run function blutopher:animations/first.snap/tree/jaw6_display_top
execute positioned as @s run tp @s ~ ~ ~ ~ ~