#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [22.5f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [67.5f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [90f,0f,0f]