#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-180f,0f,180f]
execute if score .this aj.frame matches 1 run data modify entity @s Pose.Head set value [-157.5f,0f,180f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-135f,0f,180f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-112.5f,0f,180f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-90f,0f,180f]