#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.002 ^-1.806 ^0.582 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.002 ^-1.681 ^0.442 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.002 ^-1.556 ^0.303 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.002 ^-1.431 ^0.164 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.002 ^-1.306 ^0.025 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.002 ^-1.306 ^0.025 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.002 ^-1.306 ^0.025 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.002 ^-1.306 ^0.025 ~ ~