#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function blutopher:animations/first.snap/tree/jaw2_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^0.002 ^-1.306 ^0.025 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^0.002 ^-1.306 ^0.025 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^0.002 ^-1.306 ^0.025 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^0.002 ^-1.306 ^0.025 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^0.002 ^-1.306 ^0.025 ~ ~