#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.002 ^-1.806 ^0.894 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.002 ^-1.806 ^0.894 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.002 ^-1.806 ^0.894 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.002 ^-1.67 ^0.755 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.002 ^-1.535 ^0.616 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.002 ^-1.4 ^0.477 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.002 ^-1.264 ^0.338 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.002 ^-1.129 ^0.199 ~ ~