#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [-180f,0f,180f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [-180f,0f,180f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [-165f,0f,180f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [-150f,0f,180f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [-135f,0f,-180f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [-120f,0f,180f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [-105f,0f,-180f]