#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 2 run data modify entity @s Pose.Head set value [0f,0f,0f]
execute if score .this aj.frame matches 3 run data modify entity @s Pose.Head set value [15f,0f,0f]
execute if score .this aj.frame matches 4 run data modify entity @s Pose.Head set value [30f,0f,0f]
execute if score .this aj.frame matches 5 run data modify entity @s Pose.Head set value [45f,0f,0f]
execute if score .this aj.frame matches 6 run data modify entity @s Pose.Head set value [60f,0f,0f]
execute if score .this aj.frame matches 7 run data modify entity @s Pose.Head set value [75f,0f,0f]