#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.002 ^-1.806 ^-0.774 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.002 ^-1.806 ^-0.774 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.002 ^-1.806 ^-0.774 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.002 ^-1.69 ^-0.654 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.002 ^-1.573 ^-0.535 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.002 ^-1.457 ^-0.415 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.002 ^-1.341 ^-0.295 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.002 ^-1.224 ^-0.175 ~ ~