#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^-0.002 ^-1.806 ^-0.77 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^-0.002 ^-1.806 ^-0.77 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^-0.002 ^-1.806 ^-0.77 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^-0.002 ^-1.806 ^-0.77 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^-0.002 ^-1.806 ^-0.771 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^-0.002 ^-1.696 ^-0.655 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^-0.002 ^-1.586 ^-0.539 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^-0.002 ^-1.475 ^-0.424 ~ ~