#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function blutopher:animations/first.snap/tree/jaw5_root_0-7
execute if score .this aj.frame matches 8 run tp @s ^-0.002 ^-1.365 ^-0.308 ~ ~
execute if score .this aj.frame matches 9 run tp @s ^-0.002 ^-1.255 ^-0.192 ~ ~
execute if score .this aj.frame matches 10 run tp @s ^-0.002 ^-1.145 ^-0.077 ~ ~
execute if score .this aj.frame matches 11 run tp @s ^-0.002 ^-1.145 ^-0.077 ~ ~
execute if score .this aj.frame matches 12 run tp @s ^-0.002 ^-1.145 ^-0.077 ~ ~