#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function blutopher:animations/first.snap/tree/jaw5_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [60f,0f,0f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [75f,0f,0f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [90f,0f,0f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [90f,0f,0f]