#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0..7 run function blutopher:animations/first.snap/tree/jaw6_display_0-7
execute if score .this aj.frame matches 8 run data modify entity @s Pose.Head set value [-120f,0f,180f]
execute if score .this aj.frame matches 9 run data modify entity @s Pose.Head set value [-105f,0f,-180f]
execute if score .this aj.frame matches 10 run data modify entity @s Pose.Head set value [-90f,0f,180f]
execute if score .this aj.frame matches 12 run data modify entity @s Pose.Head set value [-90f,0f,180f]