#Project generated by Animated Java (https://animated-java.dev/)

execute if score .this aj.frame matches 0 run tp @s ^0.002 ^-1.806 ^1.074 ~ ~
execute if score .this aj.frame matches 1 run tp @s ^0.002 ^-1.806 ^1.074 ~ ~
execute if score .this aj.frame matches 2 run tp @s ^0.002 ^-1.806 ^1.074 ~ ~
execute if score .this aj.frame matches 3 run tp @s ^0.002 ^-1.806 ^1.073 ~ ~
execute if score .this aj.frame matches 4 run tp @s ^0.002 ^-1.806 ^1.073 ~ ~
execute if score .this aj.frame matches 5 run tp @s ^0.002 ^-1.645 ^0.908 ~ ~
execute if score .this aj.frame matches 6 run tp @s ^0.002 ^-1.484 ^0.743 ~ ~
execute if score .this aj.frame matches 7 run tp @s ^0.002 ^-1.324 ^0.578 ~ ~